package mcp

import (
	"context"

	sdk "github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/teemo/axiomos/internal/app"
	"github.com/teemo/axiomos/internal/i18n"
)

// 目标方案（ADR 0026）：Agent「领取目标」= 提交一整套拆解，目标负责人逐条勾选后一次落库。

type planTaskIn struct {
	Key                  string   `json:"key,omitempty" jsonschema:"Key of this task inside the plan (t1, t2...); depends_on and parent_key refer to it. Generated by position when omitted"`
	Title                string   `json:"title" jsonschema:"Title"`
	Description          string   `json:"description,omitempty" jsonschema:"Description"`
	TypeName             string   `json:"type_name,omitempty" jsonschema:"Task type code name, default generic"`
	EstimateHours        *float64 `json:"estimate_hours,omitempty" jsonschema:"Estimate in hours"`
	PlannedStart         string   `json:"planned_start,omitempty" jsonschema:"Planned start YYYY-MM-DD"`
	PlannedEnd           string   `json:"planned_end,omitempty" jsonschema:"Planned end YYYY-MM-DD"`
	Priority             *int     `json:"priority,omitempty" jsonschema:"Priority 0 (highest) to 3"`
	RequiredCapabilities []string `json:"required_capabilities,omitempty" jsonschema:"Capabilities required to claim"`
	AssigneeID           string   `json:"assignee_id,omitempty" jsonschema:"Assignee (@name, ID or email); defaults to me"`
	ParentKey            string   `json:"parent_key,omitempty" jsonschema:"Key of the parent task in this plan (makes this a subtask)"`
	DependsOn            []string `json:"depends_on,omitempty" jsonschema:"Keys of tasks in this plan that must finish first"`
	// ADR 0028
	Acceptance   string            `json:"acceptance,omitempty" jsonschema:"auto (default: the system accepts when the review step's requirements are met) or human (the goal owner reviews it in the plan review)"`
	Participants map[string]string `json:"participants,omitempty" jsonschema:"Participant slot -> person (@name, ID or email) for task types with slots; omitted slots are filled with the assignee"`
}

type planMilestoneIn struct {
	Key         string `json:"key,omitempty" jsonschema:"Key inside the plan (m1, m2...); generated by position when omitted"`
	Title       string `json:"title" jsonschema:"What should be achieved by that date"`
	DueOn       string `json:"due_on" jsonschema:"Date YYYY-MM-DD"`
	Description string `json:"description,omitempty" jsonschema:"Optional description"`
}

type proposePlanIn struct {
	GoalID         string            `json:"goal_id" jsonschema:"Goal reference: the goal ID or part of its title"`
	Rationale      string            `json:"rationale,omitempty" jsonschema:"Why this breakdown: what you read, what you assume, what you left out"`
	Tasks          []planTaskIn      `json:"tasks" jsonschema:"The tasks, in the order you would present them"`
	Milestones     []planMilestoneIn `json:"milestones,omitempty" jsonschema:"Milestones to add to the goal"`
	DryRun         bool              `json:"dry_run,omitempty" jsonschema:"Only say what would happen; every check still runs, nothing is written"`
	IdempotencyKey string            `json:"idempotency_key,omitempty" jsonschema:"Client-generated key (max 64 chars): the same key within 24 hours takes effect only once"`
}

type planStatusIn struct {
	ProposalID string `json:"proposal_id" jsonschema:"The pending action ID returned by propose_goal_plan (prp_...)"`
}

var batch3Descs = map[string]i18n.Text{
	"propose_goal_plan": i18n.T("为一个目标提交一整套拆解（任务清单含依赖与上级、里程碑、理由、每个任务的验收方式与参与角色），记成一条待确认操作，由目标负责人整体批准、整体拒绝或勾掉几条再批准；批准即委托：任务一次落库、默认指派给我，并给我每个任务一份委托，之后附交付物、推进都不再逐条问人。验收方式默认 auto（要求齐了系统自动验收），要人亲自看的写 human。这就是「领取目标」：目标仍归人负责，我成为方案里那些任务的负责人。提交前先 get_goal 读清目标、get_org_context 看清团队与任务类型；需要「创建任务」授权，带里程碑还要「创建目标」授权，带子任务还要「创建子任务」授权；不看授权模式，一律经人审。",
		"Propose a full breakdown for a goal (tasks with dependencies and parents, milestones, rationale) as one pending action; the goal owner approves it as a whole, rejects it, or unticks some items and approves the rest. On approval everything is created in one go, with tasks assigned to me by default. This is what claiming a goal means: the goal stays with its human owner and I become the assignee of the plan's tasks. Read the goal with get_goal and the org with get_org_context first; requires the Create tasks grant (plus Create goals for milestones, Create subtasks for parent_key); always reviewed by a person regardless of grant mode."),
	"get_goal_plan_status": i18n.T("查一份目标方案的进展：等人确认 / 已确认 / 已拒绝（带理由）/ 已过期；已确认时带上建出来的任务与里程碑、被勾掉的键。被拒绝就读理由改方案再提，不要重提同一份。",
		"Check a goal plan: awaiting confirmation / confirmed / rejected (with reason) / expired; when confirmed it lists the created tasks and milestones and the keys that were skipped. If rejected, read the reason and propose a revised plan; do not resubmit the same one."),
}

func init() {
	for k, v := range batch3Descs {
		toolDescs[k] = v
	}
}

func addBatch3Tools(s *sdk.Server, k *kit) {
	a, sess, f := k.a, k.sess, k.f
	sdk.AddTool(s, k.tool("propose_goal_plan"), func(ctx context.Context, req *sdk.CallToolRequest, in proposePlanIn) (*sdk.CallToolResult, any, error) {
		pi := app.GoalPlanInput{Rationale: in.Rationale}
		var err error
		if pi.GoalID, err = k.gid(ctx, in.GoalID); err != nil {
			return f(err)
		}
		if pi.GoalID == "" {
			return f(app.Bad("err.goal_missing"))
		}
		for _, t := range in.Tasks {
			pt := app.PlanTask{Key: t.Key, Title: t.Title, Description: t.Description, TypeName: t.TypeName, EstimateHours: t.EstimateHours, Priority: t.Priority,
				RequiredCapabilities: t.RequiredCapabilities, ParentKey: t.ParentKey, DependsOn: t.DependsOn, Acceptance: t.Acceptance}
			if pt.AssigneeID, err = k.mid(ctx, t.AssigneeID); err != nil {
				return f(err)
			}
			for slot, who := range t.Participants {
				id, err := k.mid(ctx, who)
				if err != nil {
					return f(err)
				}
				if pt.Participants == nil {
					pt.Participants = map[string]string{}
				}
				pt.Participants[slot] = id
			}
			if pt.PlannedStart, err = parseDate(t.PlannedStart); err != nil {
				return f(err)
			}
			if pt.PlannedEnd, err = parseDate(t.PlannedEnd); err != nil {
				return f(err)
			}
			pi.Tasks = append(pi.Tasks, pt)
		}
		for _, m := range in.Milestones {
			pm := app.PlanMilestone{Key: m.Key, Title: m.Title, Description: m.Description}
			if pm.DueOn, err = parseDate(m.DueOn); err != nil {
				return f(err)
			}
			pi.Milestones = append(pi.Milestones, pm)
		}
		v, err := a.ProposeGoalPlan(ctx, k.ws(in.DryRun, in.IdempotencyKey), pi)
		if err != nil {
			return f(err)
		}
		// 方案永远是一条待确认操作：走与其他工具一样的「已提交待确认操作」返回
		return f(app.PendingOf(sess, v))
	})
	sdk.AddTool(s, k.tool("get_goal_plan_status"), func(ctx context.Context, req *sdk.CallToolRequest, in planStatusIn) (*sdk.CallToolResult, any, error) {
		out, err := a.GoalPlanStatusOf(ctx, sess, in.ProposalID)
		if err != nil {
			return f(err)
		}
		return jsonResult(out)
	})
}
